export PATH="$PATH":"$HOME/.pub-cache/bin"
export PATH="/home/amrit/.local/bin:$PATH"
export PATH="/home/amrit/.config/emacs/bin:$PATH"
# export PATH="/home/amrit/.local/bin/apache-maven-3.9.9/bin/:$PATH"
export PATH="/home/amrit/go/bin/:$PATH"
export PATH="/home/amrit/.cargo/bin:$PATH"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LOCALE_ARCHIVE="$(nix-env --installed --no-name --out-path --query glibc-locales)/lib/locale/locale-archive"
export EDITOR="/usr/bin/nvim"
export TERM=xterm-256color
export MPD_HOST=127.0.0.1
export MPD_PORT=6601
export NIX_REMOTE=daemon
export BROWSER="/usr/bin/zen-browser"
