export PATH="$PATH":"$HOME/.pub-cache/bin"
export PATH="/home/amrit/.local/bin:$PATH"
export PATH="/home/amrit/.config/emacs/bin:$PATH"
export PATH="/home/amrit/code/flutter_sdk/flutter/bin:$PATH"
export PATH="/home/amrit/go/bin/:$PATH"
export PATH="/home/amrit/.cargo/bin:$PATH"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR="/usr/bin/nvim"
export TERM=xterm-256color
# export TERM=foot
# export TERMINAL=foot
export MPD_HOST=127.0.0.1
export MPD_PORT=6601
export NIX_REMOTE=daemon
